### PR TITLE
Notifier refactor, toggle show items and more

### PR DESCRIPTION
**Pull request by synonymouse**
Hello, initially I only wanted to add the ability to interact with objects during 'show items'. But then things escalated, and I ended up formatting the stats neatly in a column and eventually completely refactored the notifier. This was my first time working with AutoIt and the game's memory, so it turned out the way it did. Here is almost the complete list of changes:

- The 'show items' feature has been revamped. It now highlights items without the need for additional 'alt' key presses. Simply pressing the hotkey once is enough. Active objects (such as portals, NPCs, etc.) will remain interactive. Due to the peculiarities of how this feature works, there is one unpleasant aspect. After death, you need to press esc a couple of times. This is something I cannot fix.

- The 'stat' and 'name' flags now neatly display text in a column. 
293689384-2548442e-6d9a-4882-96a4-bfe10eba725e

- The old version with the name and type displayed in one line was added to the options.
296023541-7fd2bf86-31b7-439b-bdf3-572ebe6c278a

- You can now create rules for specific stats on items. Use curly brackets with regex inside. If there's a match, they will be highlighted in the notification.
293691348-f9009bca-6318-4538-bafa-e2b0b052a3ca
293691295-8d238441-21ea-4cb5-a16a-1045b35ac9ef

- You can even simultaneously search for any number of same type items with different sets of stats
293695352-14241aa6-2e89-4d16-9369-ad4952bf9360
293695383-a3c4e6bc-2e0b-4b70-9b24-8c5d01224319
293695431-c8ffb804-77a6-4330-a75e-a908f90d0860

- An option for debugging the notifier has been added. It's very convenient if you need to check which rule triggers the notification.

- The program window can now be resized. Feature added primarily for the convenience of the notifier window. In other tabs of the program, bugs may occur during resizing.

- The help section in the notifier and the default rules have been updated to reflect the new features.

- The parsing of rules in the notifier has been completely overhauled. The order in which you add rules to the notifier no longer matters. It doesn't matter how many rules match a single item. Now, the rules operate based on specific criteria. The 'hide' and 'show' flags can be overwritten by another rule if they match the same item.

I strongly recommend rewriting your loot filters in a slightly different style. All changes were made with the idea that you first hide large pools of items, and then gradually reveal them as needed. Read the help section in the notifier. I have added a few examples there. Also, created a 'Default' list of rules and use it as a starting point.

Let me know if you have any comments about the code and functionality, we will discuss them if needed and will make the necessary corrections. If everything is okay, please merge and deploy the new version. After that, I'll create a forum post with the new version and the text I wrote above.

### CODE REVIEW

**Comment by synonymouse** [comment]
For a general understanding of the new version of the notifier. In the old version, when an item dropped, we compared it with each rule in the notifier. If there was a match by type, the loop stopped and an action occurred in accordance with the flags in the rule.
Now, the loop does not stop, and in the case of a match, the item is added to a separate pool of items. After that, this pool goes through several filters and gradually narrows down through a series of other loops and checks according to certain criteria, until only one item remains in the pool.

**Comment by Zahariel1942** [comment]
🥳This is a significant milestone, you're awesome! Perhaps we should increase the major version to 4?

**Comment by Zahariel1942** [comment]
We can continue the updates on the 'next' branch.

**Comment by synonymouse** [comment]
> 🥳This is a significant milestone, you're awesome! Perhaps we should increase the major version to 4?

Thanks) Yes, I think there are enough features for a major version

**Pull request merged**
